"""
Quick test to verify division expression formatting
"""
import random
import sys
sys.path.insert(0, '/root/Math-GPT/src')

from train_division import generate_division_expression

print("Testing division expression generation format:\n")
print("="*60)

for i in range(10):
    expr = generate_division_expression(num_digits=2, max_terms=4, ensure_clean_division=False)
    print(f"{i+1:2d}. {expr}")

print("="*60)
print("\nKey points:")
print("- Answers are ALWAYS decimal floats (e.g., 2.0, 3.5, 0.0847)")
print("- No division signs in answers (only in the expression)")
print("- No '=' signs can be generated by model (we add it)")
print("- Format: expression=answer (e.g., 80/5/7/27=0.0847)")
